### ISSUE TITLE
issue with dataset

### ISSUE THREAD

**Issue by domagoj-kovacevic** [hpchuck/DUMMY#1]
Hi!. the dataset you are using in this project which is obtained (i guess) by scraping strings native mobile apps on android is problematic from security perspective for lot of applications. 
Some applications keep secure keys inside such strings. For example we were notified by google that Google API key for our application  is visible on the internet with link to this repository (within one hour of repository publish). 
While in our case this is not that big of a problem since our key can be only used from our app, that might not be the case for other keys/secrets for other apps you have scraped.

**Comment by hpchuck** [comment]
Hey hi!
I understand your concern and for your information this is used just for educational purposes and I will remove it immediately now due to its security concerns. I was not aware of this issue but thanks for letting me know!
